apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: slack-midi-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: slack-midi-web
    spec:
      containers:
      - name: master
        image: gcr.io/slack-midi-1/slack-midi-web:1.0.0
        volumeMounts:
        - name: slack-midi-config
          mountPath: /etc/slack-midi-config
        env:
        - name: slack_midi_config_path
          value: /etc/slack-midi-config/solace.json
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: slack-midi-config
        secret:
          secretName: config-solace
